Repository Infineon/infineon-design-system-stencil, pull requests merged in 2023-08, with the labels that each got.

#367 324 rework update token names to the new ones
  package-lock.json
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-vue/lib/components.ts
  packages/components/package.json
  packages/components/src/components/accordion/accordion.scss
  packages/components/src/components/accordion/accordionItem.scss
  packages/components/src/components/alert/alert.scss
  packages/components/src/components/badge/badge.scss
  packages/components/src/components/breadcrumb/breadcrumb-item-label.scss
  packages/components/src/components/breadcrumb/breadcrumb-item.scss
  packages/components/src/components/breadcrumb/breadcrumb.scss
  packages/components/src/components/button/button.scss
  packages/components/src/components/card/card-headline/card-headline.scss
  packages/components/src/components/card/card-image/card-image.scss
  packages/components/src/components/card/card-links/card-links.scss
  packages/components/src/components/card/card-overline/card-overline.scss
  packages/components/src/components/card/card-text/card-text.scss
  packages/components/src/components/card/card.scss
  packages/components/src/components/checkbox/checkbox.scss
  packages/components/src/components/chips/chip.scss
  packages/components/src/components/dropdown-divider/dropdown-divider.scss
  packages/components/src/components/dropdown-item/dropdown-item.scss
  packages/components/src/components/dropdown-menu/dropdown-menu.scss
  packages/components/src/components/filter-input/filter-input.scss
  packages/components/src/components/footer/footer-column.scss
  packages/components/src/components/footer/footer.scss
  packages/components/src/components/icon-button/icon-button.scss
  packages/components/src/components/icon/infineonIconStencil.scss
  packages/components/src/components/icon/readme.md
  packages/components/src/components/icons-preview/icons-preview.scss
  packages/components/src/components/link/link.scss
  packages/components/src/components/list-group/list-group-item.scss
  packages/components/src/components/list-group/list-group-notification.scss
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/multi-select-input/multi-select-input-item.scss
  packages/components/src/components/multi-select-input/multi-select-input-item.tsx
  packages/components/src/components/multi-select-input/multi-select-input.scss
  packages/components/src/components/multi-select-input/multi-select-input.stories.ts
  packages/components/src/components/multi-select-input/multi-select-input.tsx
  packages/components/src/components/multi-select-input/readme.md
  packages/components/src/components/navbar/navbar-menu-item.scss
  packages/components/src/components/navbar/navbar.scss
  packages/components/src/components/number-indicator/number-indicator.scss
  packages/components/src/components/progress-bar/progress-bar.scss
  packages/components/src/components/radio-button/radio-button.scss
  packages/components/src/components/search-bar/search-bar.scss
  packages/components/src/components/search-field/search-field.scss
  packages/components/src/components/select-input/select-input.stories.ts
  packages/components/src/components/sidebar/sidebar-item.scss
  packages/components/src/components/sidebar/sidebar.scss
  packages/components/src/components/slider/slider.scss
  packages/components/src/components/spinner/spinner.scss
  packages/components/src/components/status/status.scss
  packages/components/src/components/switch/switch.scss
  packages/components/src/components/tabs/tabs.scss
  packages/components/src/components/tag/tag.scss
  packages/components/src/components/template-story-with-markdown/example.scss
  packages/components/src/components/text-field/text-field.scss
  packages/components/src/global/font.scss
  packages/components/src/global/global.scss
Labels: major

#364 351 implementation navbar submenu v-1
  examples/stencil-components/angular/src/app/app.component.html
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/components/Navbar/Navbar.js
  examples/wrapper-components/react-typescript/src/components/Navbar/Navbar.tsx
  examples/wrapper-components/vue-javascript/src/components/Navbar.vue
  examples/wrapper-components/vue-typescript/package-lock.json
  examples/wrapper-components/vue-typescript/src/components/Navbar.vue
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-vue/lib/components.ts
  packages/components/src/components/icon/readme.md
  packages/components/src/components/navbar/navbar-item.scss
  packages/components/src/components/navbar/navbar-item.tsx
  packages/components/src/components/navbar/navbar-menu-item.scss
  packages/components/src/components/navbar/navbar-menu-item.tsx
  packages/components/src/components/navbar/navbar-menu.scss
  packages/components/src/components/navbar/navbar-menu.tsx
  packages/components/src/components/navbar/navbar.scss
  packages/components/src/components/navbar/navbar.stories.ts
  packages/components/src/components/navbar/navbar.tsx
  packages/components/src/components/navbar/readme.md
Labels: minor

#348 added dropdown-menu doc and images
  packages/components/public-storybook/images/dropdown/dropdown-menu-filter-search-flow.png
  packages/components/public-storybook/images/dropdown/dropdown-menu-filter-search.png
  packages/components/public-storybook/images/dropdown/dropdown-menu-scroll-behavior.png
  packages/components/public-storybook/images/dropdown/dropdown-menu-sizes.png
  packages/components/public-storybook/images/dropdown/dropdown-menu-states.png
  packages/components/public-storybook/images/dropdown/dropdown-menu-trigger.png
  packages/components/public-storybook/images/dropdown/dropdown-menu-variants.png
  packages/components/src/components/dropdown/Usage.mdx
Labels: minor

#381 Documentation: number indicator
  packages/components/public-storybook/images/number-indicator/number-indicator-style.png
  packages/components/public-storybook/images/number-indicator/number-indicator-use.png
  packages/components/src/components/number-indicator/Usage.mdx
Labels: minor

#380 Documentation: Chip changed image in usage.mdx
  packages/components/public-storybook/images/chips/dropdown-chip-visible-label-states.png
Labels: minor

#395 Documentation: icon
  packages/components/public-storybook/images/icon/icon-alignment.png
  packages/components/public-storybook/images/icon/icon-color-alignment.png
  packages/components/public-storybook/images/icon/icon-size-alignment.png
  packages/components/public-storybook/images/icon/icon-sizes.png
  packages/components/public-storybook/images/icon/icon-structure.png
  packages/components/public-storybook/images/icon/icon-text-color-brand.png
  packages/components/public-storybook/images/icon/icon-text-color-dark.png
  packages/components/public-storybook/images/icon/icon-text-color-white.png
  packages/components/public-storybook/images/icon/icon-variants.png
  packages/components/src/components/icon/Usage.mdx
Labels: minor

#399 Documentation: link
  packages/components/public-storybook/images/link/link-bold-states.png
  packages/components/public-storybook/images/link/link-bold.png
  packages/components/public-storybook/images/link/link-font-size-alignment.png
  packages/components/public-storybook/images/link/link-icon-left.png
  packages/components/public-storybook/images/link/link-icon-placement-left.png
  packages/components/public-storybook/images/link/link-icon-placement-right.png
  packages/components/public-storybook/images/link/link-icon-right.png
  packages/components/public-storybook/images/link/link-inline-error-states.png
  packages/components/public-storybook/images/link/link-inline-error.png
  packages/components/public-storybook/images/link/link-inline-states.png
  packages/components/public-storybook/images/link/link-inline.png
  packages/components/public-storybook/images/link/link-menu-states.png
  packages/components/public-storybook/images/link/link-menu.png
  packages/components/public-storybook/images/link/link-mouse-interaction.png
  packages/components/public-storybook/images/link/link-sizes.png
  packages/components/public-storybook/images/link/link-title-states.png
  packages/components/public-storybook/images/link/link-title.png
  packages/components/src/components/link/Usage.mdx
Labels: minor

#408 Documentation: checkbox update
  packages/components/src/components/checkbox/Usage.mdx
Labels: minor

#404 Documentation: footer
  packages/components/public-storybook/images/footer/footer-default-anatomy.png
  packages/components/public-storybook/images/footer/footer-large.png
  packages/components/public-storybook/images/footer/footer-medium.png
  packages/components/public-storybook/images/footer/footer-mobile.png
  packages/components/public-storybook/images/footer/footer-sidebar.png
  packages/components/public-storybook/images/footer/footer-small.png
  packages/components/src/components/footer/Usage.mdx
Labels: minor

#410 Documentation: button update
  packages/components/src/components/button/Usage.mdx
Labels: minor

#405 Documentation: progress bar
  packages/components/public-storybook/images/progress-bar/progressbar-20px.png
  packages/components/public-storybook/images/progress-bar/progressbar-4px.png
  packages/components/public-storybook/images/progress-bar/progressbar-anatomy.png
  packages/components/src/components/progress-bar/Usage.mdx
Labels: minor

#328 Component: Single-Select using ChoicesJs +Multiselect
  .gitignore
  examples/stencil-components/angular/src/app/app.component.html
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/MultiSelect/MultiSelect.js
  examples/wrapper-components/react-javascript/src/components/SingleSelect/SingleSelect.js
  examples/wrapper-components/vue-javascript/index.html
  examples/wrapper-components/vue-javascript/package-lock.json
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/MultiSelect.vue
  examples/wrapper-components/vue-javascript/src/components/SingleSelect.vue
  examples/wrapper-components/vue-javascript/vite.config.js
  examples/wrapper-components/vue-typescript/src/components/HelloWorld.vue
  package-lock.json
  package.json
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-vue/lib/components.ts
  packages/components/framework-output-targets.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components/breadcrumb/breadcrumb.tsx
  packages/components/src/components/checkbox/checkbox.scss
  packages/components/src/components/checkbox/checkbox.stories.ts
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/checkbox/readme.md
  packages/components/src/components/dropdown-menu/dropdown-menu.stories.ts
  packages/components/src/components/dropdown/dropdown.stories.ts
  packages/components/src/components/icon/readme.md
  packages/components/src/components/modal/modal.tsx
  packages/components/src/components/multi-select-input/multi-select-input.stories.ts
  packages/components/src/components/multiselect/interfaces.tsx
  packages/components/src/components/multiselect/multiselect.e2e.ts
  packages/components/src/components/multiselect/multiselect.scss
  packages/components/src/components/multiselect/multiselect.stories.ts
  packages/components/src/components/multiselect/multiselect.tsx
  packages/components/src/components/multiselect/readme.md
  packages/components/src/components/select-input/readme.md
  packages/components/src/components/select-input/select-input.scss
  packages/components/src/components/select-input/select-input.tsx
  packages/components/src/components/select/interfaces.tsx
  packages/components/src/components/select/readme.md
  packages/components/src/components/select/select.e2e.ts
  packages/components/src/components/select/select.scss
  packages/components/src/components/select/select.stories.ts
  packages/components/src/components/select/select.tsx
  packages/components/src/components/select/types/choices.d.ts
  packages/components/src/components/select/utils.ts
  packages/components/stencil.config.ts
  tsconfig.base.json
Labels: minor

#411 392 code quality spinner missing e2e tests
  examples/wrapper-components/vue-javascript/vite.config.js
  packages/components/src/components/spinner/spinner.e2e.ts
  packages/components/src/components/status/status.e2e.ts
Labels: patch

#415 e2e tests added for chip component
  packages/components/src/components/chips/chip.e2e.ts
Labels: patch

#414 Documentation: tag
  packages/components/public-storybook/images/tag/tag-alignment.png
  packages/components/public-storybook/images/tag/tag-anatomy.png
  packages/components/public-storybook/images/tag/tag-states.png
  packages/components/public-storybook/images/tag/tag-wraping.png
  packages/components/src/components/tag/Usage.mdx
Labels: minor

#412 Documentation: breadcrumb
  packages/components/public-storybook/images/breadcrumb/breadcrumb-anatomy.png
  packages/components/public-storybook/images/breadcrumb/breadcrumb-mouse-interaction.png
  packages/components/public-storybook/images/breadcrumb/breadcrumb-positioning-desktop.png
  packages/components/public-storybook/images/breadcrumb/breadcrumb-positioning-mobile.png
  packages/components/public-storybook/images/breadcrumb/breadcrumb-states.png
  packages/components/src/components/breadcrumb/Usage.mdx
Labels: minor

#420 Code quality: Single-select - replaced document with this.root to not query the document
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/vue-javascript/src/components/SingleSelect.vue
  packages/components/src/components/select/select.tsx
Labels: minor

#421 Bugfix: Single-Select - fix for the lost focus when toggling the dropdown and the select is a…
  packages/components/src/components/select/select.tsx
Labels: patch

#428 Documentation: modal update
  packages/components/src/components/modal/Usage.mdx
Labels: minor

#425 Documentation: button update
  packages/components/public-storybook/images/button/button-variant-error.png
  packages/components/public-storybook/images/button/button-variant-secondary.png
  packages/components/public-storybook/images/button/error-button-states.png
  packages/components/public-storybook/images/button/secondary-button-states.png
  packages/components/src/components/button/Usage.mdx
Labels: minor

#431 Documentation: link update
  packages/components/src/components/link/Usage.mdx
Labels: minor

#433 Documentation: tag update
  packages/components/src/components/tag/Usage.mdx
Labels: minor

#396 Table using agGrid library
  .github/workflows/test.yml
  examples/stencil-components/angular/src/app/app.component.html
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/package.json
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/BasicTable/BasicTable.js
  examples/wrapper-components/vue-javascript/package-lock.json
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/BasicTable.vue
  lerna.json
  package-lock.json
  package.json
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-react/package-lock.json
  packages/components-react/package.json
  packages/components-vue/lib/components.ts
  packages/components-vue/package-lock.json
  packages/components-vue/package.json
  packages/components/framework-output-targets.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components/select-input/select-input.stories.ts
  packages/components/src/components/table-basic-version/Development.mdx
  packages/components/src/components/table-basic-version/interfaces.ts
  packages/components/src/components/table-basic-version/readme.md
  packages/components/src/components/table-basic-version/table.e2e.ts
  packages/components/src/components/table-basic-version/table.scss
  packages/components/src/components/table-basic-version/table.stories.ts
  packages/components/src/components/table-basic-version/table.tsx
  packages/components/src/components/table/Development.mdx
  packages/components/src/components/table/buttonCellRenderer.ts
  packages/components/src/components/table/interfaces.ts
  packages/components/src/components/table/readme.md
  packages/components/src/components/table/table.scss
  packages/components/src/components/table/table.stories.ts
  packages/components/src/components/table/table.tsx
Labels: minor

#382 195 implementation tooltip
  examples/stencil-components/angular/package-lock.json
  examples/stencil-components/angular/package.json
  examples/stencil-components/angular/src/app/app.component.html
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/package.json
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/Tooltip/Tooltip.js
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/MultiSelect.vue
  examples/wrapper-components/vue-javascript/src/components/SingleSelect.vue
  examples/wrapper-components/vue-javascript/src/components/TextField.vue
  examples/wrapper-components/vue-javascript/src/components/Tooltip.vue
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-vue/lib/components.ts
  packages/components/src/components/icon/readme.md
  packages/components/src/components/tooltip/readme.md
  packages/components/src/components/tooltip/tooltip.e2e.ts
  packages/components/src/components/tooltip/tooltip.scss
  packages/components/src/components/tooltip/tooltip.stories.ts
  packages/components/src/components/tooltip/tooltip.tsx
  packages/components/src/index.html
Labels: minor
