Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-01, with the labels that each got.

#791 Sidebar: v-2 copy version
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/src/components/Sidebar/Sidebar.js
  examples/wrapper-components/vue-javascript/package-lock.json
  examples/wrapper-components/vue-javascript/src/components/Sidebar.vue
  examples/wrapper-components/vue-javascript/src/main.js
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-angular/projects/my-app/src/app/app.component.ts
  packages/components-vue/lib/components.ts
  packages/components/src/components/alert/alert.tsx
  packages/components/src/components/number-indicator/readme.md
  packages/components/src/components/sidebar/Development.mdx
  packages/components/src/components/sidebar/readme.md
  packages/components/src/components/sidebar/sidebar-item.scss
  packages/components/src/components/sidebar/sidebar-item.tsx
  packages/components/src/components/sidebar/sidebar.scss
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/components/sidebar/sidebar.tsx
  packages/components/src/index.html
Labels: minor

#857 Using CSS Custom Properties to enable overwriting the default font
  examples/wrapper-components/react-javascript/src/App.scss
  examples/wrapper-components/vue-javascript/src/assets/base.scss
  packages/components/src/global/font.scss
  packages/components/src/stories/setup-and-installation/GettingStarted.stories.mdx
Labels: patch

#859 bugfix in master .yml
  .github/workflows/shipit_master_and_example_apps_deployment.yml
Labels: patch

#861 bugfix in master .yml
  .github/workflows/shipit_master_and_example_apps_deployment.yml
Labels: patch

#856 Update navbar.stories.ts Fixed #844
  packages/components/src/components/navbar/navbar.stories.ts
Labels: patch

#840 Z index adjusted to web standards
  package-lock.json
  packages/components-angular/package.json
  packages/components/src/components/dropdown/dropdown-menu/dropdown-menu.scss
  packages/components/src/components/icons-preview/icons-preview.scss
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/navbar/navbar-menu.scss
  packages/components/src/components/navbar/navbar.scss
  packages/components/src/components/tooltip/tooltip.scss
Labels: bug

#876 Updated scss of modal to fix #875
  packages/components/src/components/modal/modal.scss
  packages/components/src/index.html
Labels: bug

#855 Update card.stories.ts to fix #806
  packages/components/src/components/card/card.stories.ts
Labels: enhancement, patch

#883 Sidebar: inner content height is now flexible
  packages/components/src/components/sidebar/sidebar.scss
Labels: bug

#882 Added background color to progress bar
  packages/components/src/components/progress-bar/progress-bar.scss
Labels: minor

#902 Card: Card is clickable even without href
  packages/components/src/components/card/card.tsx
  packages/components/src/index.html
Labels: bug

#903 Spinner: added an inverted prop
  package-lock.json
  packages/components-vue/lib/components.ts
  packages/components/src/components/spinner/readme.md
  packages/components/src/components/spinner/spinner.scss
  packages/components/src/components/spinner/spinner.tsx
  packages/components/src/index.html
Labels: minor

#874 Added fullWidth prop on button component
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/components/Button/button.js
  package-lock.json
  packages/components-vue/lib/components.ts
  packages/components/src/components/button/button.scss
  packages/components/src/components/button/button.stories.ts
  packages/components/src/components/button/button.tsx
  packages/components/src/components/button/readme.md
  packages/components/src/index.html
Labels: enhancement, minor

#890 Accordion: dynamic height not working with content wrapper
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/src/components/Accordion/Accordion.js
  examples/wrapper-components/vue-javascript/package-lock.json
  examples/wrapper-components/vue-javascript/src/components/Accordion.vue
  package-lock.json
  packages/components/src/components/accordion/Development.mdx
  packages/components/src/components/accordion/accordion.stories.tsx
  packages/components/src/components/accordion/accordionItem.tsx
  packages/components/src/index.html
Labels: minor

#753 added missing bg color for single and multiselect
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/src/components/MultiSelect/MultiSelect.js
  examples/wrapper-components/react-javascript/src/components/SingleSelect/SingleSelect.js
  examples/wrapper-components/vue-javascript/package-lock.json
  package-lock.json
  packages/components/src/components/select/multi-select/multiselect.scss
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/single-select/select.scss
Labels: patch

#917 Added closable property to the alert component
  packages/components-vue/lib/components.ts
  packages/components/src/components/alert/alert.stories.ts
  packages/components/src/components/alert/alert.tsx
  packages/components/src/components/alert/readme.md
Labels: patch

#920 Card: when not clickable, no hover state
  package-lock.json
  packages/components/src/components/card/card.scss
  packages/components/src/components/card/card.tsx
Labels: patch

#926 Alert: optimized code and updated storybook
  package-lock.json
  packages/components/src/components/alert/alert.scss
  packages/components/src/components/alert/alert.stories.ts
  packages/components/src/components/alert/alert.tsx
Labels: patch

#915 Font Family can now be modified by user via CSS custom properties
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/Badge/Badge.js
  examples/wrapper-components/react-javascript/src/components/ProgressBar/ProgressBar.js
  examples/wrapper-components/vue-javascript/src/components/Badge.vue
  package-lock.json
  package.json
  packages/components/.storybook/exported-sass-array.json
  packages/components/.storybook/ifxTheme.js
  packages/components/.storybook/main.js
  packages/components/.storybook/manager.js
  packages/components/.storybook/preview.js
  packages/components/package.json
  packages/components/src/components/accordion/accordion.scss
  packages/components/src/components/accordion/accordionItem.scss
  packages/components/src/components/alert/alert.scss
  packages/components/src/components/badge/badge.scss
  packages/components/src/components/breadcrumb/breadcrumb-item.scss
  packages/components/src/components/breadcrumb/breadcrumb.scss
  packages/components/src/components/button/button.scss
  packages/components/src/components/card/card-headline/card-headline.scss
  packages/components/src/components/card/card.scss
  packages/components/src/components/checkbox/checkbox.scss
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/chips/chip.scss
  packages/components/src/components/dropdown/dropdown-header/dropdown-header.scss
  packages/components/src/components/dropdown/dropdown-item/dropdown-item.scss
  packages/components/src/components/dropdown/dropdown-menu/dropdown-menu.scss
  packages/components/src/components/footer/footer-column.scss
  packages/components/src/components/footer/footer.scss
  packages/components/src/components/icon-button/icon-button.scss
  packages/components/src/components/link/link.scss
  packages/components/src/components/list-group/list-group-item.scss
  packages/components/src/components/list-group/list-group-notification.scss
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/navbar/navbar-item.scss
  packages/components/src/components/navbar/navbar-menu-item.scss
  packages/components/src/components/navbar/navbar-menu.scss
  packages/components/src/components/navbar/navbar.scss
  packages/components/src/components/number-indicator/number-indicator.scss
  packages/components/src/components/pagination/pagination.scss
  packages/components/src/components/progress-bar/progress-bar.scss
  packages/components/src/components/radio-button/radio-button.scss
  packages/components/src/components/search-bar/search-bar.scss
  packages/components/src/components/search-field/search-field.scss
  packages/components/src/components/select/multi-select/multiselect.scss
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/sidebar/sidebar-item.scss
  packages/components/src/components/sidebar/sidebar.scss
  packages/components/src/components/spinner/spinner.scss
  packages/components/src/components/status/status.scss
  packages/components/src/components/table-basic-version/table.scss
  packages/components/src/components/table/table.scss
  packages/components/src/components/tabs/tabs.scss
  packages/components/src/components/tag/tag.scss
  packages/components/src/components/text-field/text-field.scss
  packages/components/src/components/tooltip/tooltip.scss
  packages/components/src/global/font.scss
  packages/components/src/global/global.scss
Labels: patch

#940 fixed master deployment file
  .github/workflows/shipit_master_and_example_apps_deployment.yml
Labels: patch

#928 Checkbox: optimized internal state usage
  packages/components/src/components/checkbox/checkbox.tsx
Labels: patch

#945 Bugfix: Setting activeTabIndex from outside
  examples/wrapper-components/vue-javascript/src/components/Tabs.vue
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-angular/projects/my-app/src/app/app.component.ts
  packages/components-angular/projects/my-app/src/index.html
  packages/components/src/components/tabs/tabs.tsx
Labels: patch

#946 Footer url props added for terms, imprint, etc.
  .github/workflows/github_pages_storybook_master.yml
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/components/Footer/Footer.js
  examples/wrapper-components/vue-javascript/src/components/Footer.vue
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-vue/lib/components.ts
  packages/components/.storybook/preview.js
  packages/components/src/components/footer/footer.stories.ts
  packages/components/src/components/footer/footer.tsx
  packages/components/src/components/link/link.tsx
  packages/components/src/components/link/readme.md
Labels: minor
