Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-10, with the labels that each got.

#1408 Stepper: implemented `disabled` prop for ifx-step
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/link/readme.md
  packages/components/src/components/stepper/interfaces.tsx
  packages/components/src/components/stepper/readme.md
  packages/components/src/components/stepper/step/readme.md
  packages/components/src/components/stepper/step/step.scss
  packages/components/src/components/stepper/step/step.tsx
  packages/components/src/components/stepper/stepper.stories.ts
  packages/components/src/components/stepper/stepper.tsx
Labels: minor

#1452 Storybook: update theme to Infineon branding
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/.storybook/ifxTheme.js
  packages/components/.storybook/ifxTheme.ts
  packages/components/.storybook/public/logo.png
  packages/components/package.json
Labels: enhancement, minor

#1482 Tabs: fixed storybook page bug
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/tabs/tabs.stories.ts
Labels: documentation, patch

#1464 Stepper: Added documentationv in Storybook
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/stepper/stepper-compact-stepper.png
  packages/components/public-storybook/images/stepper/stepper-editable-steppers.png
  packages/components/public-storybook/images/stepper/stepper-non-editable-steppers.png
  packages/components/public-storybook/images/stepper/stepper-steps-states.png
  packages/components/public-storybook/images/stepper/stepper-vertical-stepper.png
  packages/components/src/components/stepper/Usage.mdx
Labels: minor

#1517 Accordion: Removed redundant code
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/accordion.stories.tsx
  packages/components/src/components/accordion/accordionItem.tsx
  packages/components/src/components/accordion/readme.md
Labels: minor

#1456 Text-field: made asterisk symbol red when error is true
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/text-field/text-field.scss
  packages/components/src/components/text-field/text-field.tsx
Labels: patch

#1494 Card: removed unnecessary error message on horizontal variant
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/card/card.tsx
  packages/components/src/index.html
Labels: patch

#1519 Icon-button: event not emitted anymore when disabled
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icon-button/icon-button.e2e.ts
  packages/components/src/components/icon-button/icon-button.tsx
  packages/components/src/index.html
Labels: patch

#1481 Sidebar: number-indicator not showing anymore when empty
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/navigation/sidebar/sidebar-item.tsx
  packages/components/src/components/number-indicator/number-indicator.scss
  packages/components/src/components/number-indicator/number-indicator.tsx
  packages/components/src/index.html
Labels: patch

#1525 Stepper: skip step if disabled
  examples/wrapper-components/react-javascript/src/components/Stepper/Stepper.js
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/src/components/Stepper/Stepper.jsx
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/stepper/stepper.tsx
  packages/components/src/index.html
Labels: minor

#1530 docs(1529): link selected control in Chip story with the component
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/chip/chip.stories.ts
Labels: documentation, patch

#1532 Tabs: prevent active tab from becoming negative index which causes error in React
  examples/wrapper-components/react-vite-js/src/components/Tabs/Tabs.jsx
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/tabs/tabs.tsx
Labels: patch

#1474 Enhancement: Add content-switcher component
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/ContentSwitcher/ContentSwitcher.js
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/App.jsx
  examples/wrapper-components/react-vite-js/src/components/ContentSwitcher/ContentSwitcher.jsx
  examples/wrapper-components/react-vite-js/vite.config.js
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/ContentSwitcher.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/content-switcher/content-switcher-item.scss
  packages/components/src/components/content-switcher/content-switcher-item.tsx
  packages/components/src/components/content-switcher/content-switcher.e2e.ts
  packages/components/src/components/content-switcher/content-switcher.scss
  packages/components/src/components/content-switcher/content-switcher.stories.ts
  packages/components/src/components/content-switcher/content-switcher.tsx
  packages/components/src/components/content-switcher/readme.md
Labels: enhancement, minor

#1493 feat(1447): Add Notification Component
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/package-lock.json
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/Notification/Notification.js
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/App.jsx
  examples/wrapper-components/react-vite-js/src/components/Notification/Notification.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/Notification.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icon/readme.md
  packages/components/src/components/link/readme.md
  packages/components/src/components/notification/notification.e2e.ts
  packages/components/src/components/notification/notification.scss
  packages/components/src/components/notification/notification.stories.ts
  packages/components/src/components/notification/notification.tsx
  packages/components/src/components/notification/readme.md
Labels: minor

#1533 Content Switcher: Added documentation
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/.storybook/main.js
  packages/components/package.json
  packages/components/public-storybook/images/content-switcher/content-switcher-anatomy.png
  packages/components/public-storybook/images/content-switcher/content-switcher-mouse-interaction.png
  packages/components/public-storybook/images/content-switcher/content-switcher-states.png
  packages/components/public-storybook/images/content-switcher/content-switcher-variants.png
  packages/components/src/components/content-switcher/Usage.mdx
  packages/components/src/components/overview-table/overview-table.tsx
Labels: minor

#1544 Removed deprecated cpx and adopted ncp dependency
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: minor

#1503 Accessibility enhancement added to Accordion
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/accordion.stories.tsx
  packages/components/src/components/accordion/accordion.tsx
  packages/components/src/components/accordion/accordionItem.scss
  packages/components/src/components/accordion/accordionItem.tsx
  packages/components/src/components/accordion/readme.md
Labels: enhancement, minor

#1523 Created custom templates for GitHub issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/component_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: minor

#1545 Accessibility enhancement added to Alert
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/accordionItem.tsx
  packages/components/src/components/accordion/readme.md
  packages/components/src/components/alert/alert.scss
  packages/components/src/components/alert/alert.stories.ts
  packages/components/src/components/alert/alert.tsx
  packages/components/src/components/alert/readme.md
Labels: minor

#1425 New component: Segmented controls
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  .github/workflows/test.yml
  examples/wrapper-components/react-javascript/package.json
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/SegmentedControl/SegmentedControl.jsx
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/App.jsx
  examples/wrapper-components/react-vite-js/src/components/SegmentedControl/SegmentedControl.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/SegmentedControl.vue
  lerna.json
  package-lock.json
  package.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/CHANGELOG.md
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/accordionItem.tsx
  packages/components/src/components/icon/readme.md
  packages/components/src/components/segmented-control/readme.md
  packages/components/src/components/segmented-control/segment/readme.md
  packages/components/src/components/segmented-control/segment/segment.scss
  packages/components/src/components/segmented-control/segment/segment.tsx
  packages/components/src/components/segmented-control/segmented-control.e2e.ts
  packages/components/src/components/segmented-control/segmented-control.scss
  packages/components/src/components/segmented-control/segmented-control.stories.ts
  packages/components/src/components/segmented-control/segmented-control.tsx
  packages/components/src/index.html
Labels: minor
