Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-12, with the labels that each got.

#1625 Updated GitHub issues' templates to add more description and make techstack environment required field
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: enhancement, patch

#1627 Accessibility enhancement added to datepicker
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/date-picker/date-picker.scss
  packages/components/src/components/date-picker/date-picker.tsx
  packages/components/src/index.html
Labels: enhancement, minor

#1630 Alert: Updated documentation
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/alert/alert-anatomy.png
  packages/components/public-storybook/images/alert/alert-placement-desktop.png
  packages/components/public-storybook/images/alert/alert-placement-mobile.png
  packages/components/public-storybook/images/alert/alert-variant-brand.png
  packages/components/public-storybook/images/alert/alert-variant-danger.png
  packages/components/public-storybook/images/alert/alert-variant-neutral.png
  packages/components/public-storybook/images/alert/alert-variant-success.png
  packages/components/public-storybook/images/alert/alert-variant-warning.png
  packages/components/src/index.html
Labels: patch

#1633 (internal dev update) Updated package scripts to run example apps from root
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  package.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/overview-table/overview-table.tsx
Labels: enhancement, minor

#1638 Navbar: added condition that checks if right-items exist before querying them to prevent edge case errors
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/navigation/navbar/navbar.tsx
Labels: patch

#1639 Single-select: removes the close button on small resolution and adds it when default option is selected
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/pagination/pagination.tsx
  packages/components/src/components/select/single-select/readme.md
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/select/single-select/select.tsx
Labels: minor

#1626 Update tokens library to latest version
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/.storybook/exported-sass-array.json
  packages/components/package.json
Labels: major

#1600 Grid: Updated documentation
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/grid/grid-4px-example.png
  packages/components/public-storybook/images/grid/grid-placement.png
  packages/components/public-storybook/images/grid/grid-sizes.png
  packages/components/src/stories/foundations/Grid.mdx
Labels: minor

#1641 Single-select: truncating selected option
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/select/single-select/select.tsx
Labels: minor

#1642 Basic-table: Reverts back noRowsOverlayComponentParams prop
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-basic-version/table.tsx
Labels: minor

#1645 Table components: makes text selectable
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-advanced-version/table.tsx
  packages/components/src/components/table-basic-version/table.tsx
Labels: minor

#1653 Basic-table: fixes error on initial empty table load
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-basic-version/table.tsx
Labels: minor

#1656 Advanced-table: removes bug where default sort order icon appears
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-advanced-version/table.scss
Labels: patch

#1659 Removes list-group from internal project
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/list-group/list-group-item.scss
  packages/components/src/components/list-group/list-group-item.tsx
  packages/components/src/components/list-group/list-group-notification.scss
  packages/components/src/components/list-group/list-group-notification.tsx
  packages/components/src/components/list-group/list-group.scss
  packages/components/src/components/list-group/list-group.tsx
  packages/components/src/components/list-group/readme.md
  packages/components/src/components/number-indicator/readme.md
Labels: minor

#1658 Single-select: clears the field only on options update (prevents double re-rendering of component)
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/single-select/select.tsx
Labels: minor

#1587 Advanced table: restores column divider, and enables customization on nested button (href / event handler)
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/components/Table/Table.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/components/AdvancedTable.vue
  examples/wrapper-components/vue-javascript/src/components/FilterTypeGroup.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-angular/projects/my-app/src/app/app.component.ts
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-advanced-version/Development.mdx
  packages/components/src/components/table-advanced-version/buttonCellRenderer.ts
  packages/components/src/components/table-advanced-version/interfaces.ts
  packages/components/src/components/table-advanced-version/readme.md
  packages/components/src/components/table-advanced-version/table.scss
  packages/components/src/components/table-advanced-version/table.stories.ts
  packages/components/src/components/table-advanced-version/table.tsx
  packages/components/src/components/table-basic-version/table.scss
Labels: minor

#1663 Tabs: removes focus state on mouse click
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/.storybook/main.js
  packages/components/package.json
  packages/components/src/components/tabs/tabs.tsx
Labels: patch
