Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-08, with the labels that each got.

#1404 Tooltip: implemented min and max width
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/tooltip/tooltip.scss
  packages/components/src/components/tooltip/tooltip.stories.ts
Labels: enhancement, minor

#1405 Multiselect: selected state of the passed array of items is now reflected on the rendered component
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/multi-select/multiselect.stories.ts
  packages/components/src/components/select/multi-select/multiselect.tsx
Labels: bug, patch

#1412 Removed dependabot script due to updated deployment actions taking care of versioning
  .github/dependabot.yml
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch

#1410 Enhancement: add matomo tracking logic inside build process
  examples/stencil-components/vanilla-cdn/index.html
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/framework-output-targets.ts
  packages/components/package.json
  packages/components/rollup-plugin-inject-tracking.js
  packages/components/src/components/accordion/accordion.tsx
  packages/components/src/components/alert/alert.tsx
  packages/components/src/components/badge/badge.tsx
  packages/components/src/components/breadcrumb/breadcrumb.tsx
  packages/components/src/components/button/button.tsx
  packages/components/src/components/card/card.tsx
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/chips/chip.tsx
  packages/components/src/components/date-picker/date-picker.tsx
  packages/components/src/components/dropdown/dropdown.tsx
  packages/components/src/components/footer/footer.tsx
  packages/components/src/components/icon-button/icon-button.tsx
  packages/components/src/components/icon/infineonIconStencil.tsx
  packages/components/src/components/link/link.tsx
  packages/components/src/components/list-group/list-group.tsx
  packages/components/src/components/modal/modal.tsx
  packages/components/src/components/navigation/navbar/navbar.tsx
  packages/components/src/components/navigation/sidebar/sidebar.tsx
  packages/components/src/components/number-indicator/number-indicator.tsx
  packages/components/src/components/pagination/pagination.tsx
  packages/components/src/components/progress-bar/progress-bar.tsx
  packages/components/src/components/radio-button/radio-button.tsx
  packages/components/src/components/search-bar/search-bar.tsx
  packages/components/src/components/search-field/search-field.tsx
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/single-select/select.tsx
  packages/components/src/components/slider/slider.tsx
  packages/components/src/components/spinner/spinner.tsx
  packages/components/src/components/status/status.tsx
  packages/components/src/components/stepper/stepper.tsx
  packages/components/src/components/switch/switch.tsx
  packages/components/src/components/table-basic-version/table.tsx
  packages/components/src/components/table/table.tsx
  packages/components/src/components/tabs/tabs.tsx
  packages/components/src/components/tag/tag.tsx
  packages/components/src/components/text-field/text-field.tsx
  packages/components/src/components/tooltip/tooltip.tsx
  packages/components/src/global/utils/tracking.ts
  packages/components/src/index.html
  packages/components/src/index.ts
  packages/components/stencil.config.ts
  packages/components/tsconfig.json
  packages/components/types/global.d.ts
Labels: minor

#1415 Dropdown: Optimized dropdown story
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/dropdown/dropdown.stories.ts
Labels: patch

#1422 Tracking needs to be removed
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/rollup-plugin-inject-tracking.js
  packages/components/src/components/accordion/accordion.tsx
  packages/components/src/components/alert/alert.tsx
  packages/components/src/components/badge/badge.tsx
  packages/components/src/components/breadcrumb/breadcrumb.tsx
  packages/components/src/components/button/button.tsx
  packages/components/src/components/card/card.tsx
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/chips/chip.tsx
  packages/components/src/components/date-picker/date-picker.tsx
  packages/components/src/components/dropdown/dropdown.tsx
  packages/components/src/components/footer/footer.tsx
  packages/components/src/components/icon-button/icon-button.tsx
  packages/components/src/components/icon/infineonIconStencil.tsx
  packages/components/src/components/link/link.tsx
  packages/components/src/components/list-group/list-group.tsx
  packages/components/src/components/modal/modal.tsx
  packages/components/src/components/navigation/navbar/navbar.tsx
  packages/components/src/components/navigation/sidebar/sidebar.tsx
  packages/components/src/components/number-indicator/number-indicator.tsx
  packages/components/src/components/pagination/pagination.tsx
  packages/components/src/components/progress-bar/progress-bar.tsx
  packages/components/src/components/radio-button/radio-button.tsx
  packages/components/src/components/search-bar/search-bar.tsx
  packages/components/src/components/search-field/search-field.tsx
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/single-select/select.tsx
  packages/components/src/components/slider/slider.tsx
  packages/components/src/components/spinner/spinner.tsx
  packages/components/src/components/status/status.tsx
  packages/components/src/components/stepper/stepper.tsx
  packages/components/src/components/switch/switch.tsx
  packages/components/src/components/table-basic-version/table.tsx
  packages/components/src/components/table/table.tsx
  packages/components/src/components/tabs/tabs.tsx
  packages/components/src/components/tag/tag.tsx
  packages/components/src/components/text-field/text-field.tsx
  packages/components/src/components/tooltip/tooltip.tsx
  packages/components/src/global/utils/tracking.ts
  packages/components/stencil.config.ts
Labels: minor

#1423 Enhancement: upgraded to angular 18
  lerna.json
  package-lock.json
  packages/components-angular/angular.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: minor

#1414 SingleSelect: Clean Up and Bug Fix
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/App.scss
  examples/wrapper-components/react-javascript/src/components/MultiSelect/MultiSelect.js
  examples/wrapper-components/vue-javascript/src/assets/base.scss
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/styles.scss
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/pagination/pagination.tsx
  packages/components/src/components/select/multi-select/multiselect.scss
  packages/components/src/components/select/multi-select/multiselect.stories.ts
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/single-select/readme.md
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/select/single-select/select.tsx
  packages/components/src/components/select/single-select/utils.ts
Labels: bug, patch

#1428 Single Select: removed unnecessary code
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/single-select/interfaces.tsx
  packages/components/src/components/select/single-select/readme.md
  packages/components/src/components/select/single-select/select.tsx
Labels: patch

#1430 Checkbox: removed fixed height
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/checkbox/checkbox.scss
Labels: bug

#1444 Icon component: removed unnecessary console error
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icon/infineonIconStencil.tsx
Labels: patch
