Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-07, with the labels that each got.

#1332 Alert: added box shadow
  packages/components/src/components/alert/alert.scss
Labels: minor

#1346 Navbar-profile: implemented a tooltip for username
  package-lock.json
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar-profile.tsx
  packages/components/src/components/navigation/navbar/navbar.stories.ts
  packages/components/src/components/navigation/navbar/readme.md
Labels: minor

#1343 Navbar: enhanced customization of profile image
  examples/wrapper-components/react-javascript/src/components/Navbar/Navbar.js
  package-lock.json
  packages/components/public-storybook/images/navbar/48px-profile.png
  packages/components/src/components/navigation/navbar/Development.mdx
  packages/components/src/components/navigation/navbar/assets/default_image.png
  packages/components/src/components/navigation/navbar/assets/default_profile2.png
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar-profile.tsx
  packages/components/src/components/navigation/navbar/navbar.stories.ts
Labels: minor

#1356 Navbar: restored old changes regarding profile image hover and username
  examples/wrapper-components/react-javascript/src/components/Navbar/Navbar.js
  packages/components/src/components/navigation/navbar/Development.mdx
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar.stories.ts
Labels: patch

#1358 Icon component: removed error message when no icon specified
  packages/components/src/components/icon/infineonIconStencil.tsx
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar-profile.tsx
Labels: minor

#1331 Stepper: enhanced step customization
  examples/wrapper-components/react-javascript/src/components/Stepper/Stepper.js
  examples/wrapper-components/react-javascript/src/components/Stepper/stepper.scss
  packages/components/src/components/link/readme.md
  packages/components/src/components/stepper/Development.mdx
  packages/components/src/components/stepper/interfaces.tsx
  packages/components/src/components/stepper/readme.md
  packages/components/src/components/stepper/step/readme.md
  packages/components/src/components/stepper/step/step.scss
  packages/components/src/components/stepper/step/step.tsx
  packages/components/src/components/stepper/stepper.e2e.ts
  packages/components/src/components/stepper/stepper.stories.ts
  packages/components/src/components/stepper/stepper.tsx
Labels: minor

#1366 Bugfix: adjusted the deployment bugfix for the github action master workflow
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch

#1364 Icon preview: out of sync with the icon library
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icons-preview/icons-preview.scss
  packages/components/src/components/stepper/Development.mdx
  packages/components/src/index.html
Labels: minor

#1284 Form integration for radio-button, checkbox, text-field, switch and date-picker
  packages/components/src/components/checkbox/checkbox.e2e.ts
  packages/components/src/components/checkbox/checkbox.stories.ts
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/checkbox/readme.md
  packages/components/src/components/date-picker/date-picker.e2e.ts
  packages/components/src/components/date-picker/date-picker.stories.ts
  packages/components/src/components/date-picker/date-picker.tsx
  packages/components/src/components/date-picker/readme.md
  packages/components/src/components/radio-button/radio-button.e2e.ts
  packages/components/src/components/radio-button/radio-button.stories.ts
  packages/components/src/components/radio-button/radio-button.tsx
  packages/components/src/components/switch/switch.e2e.ts
  packages/components/src/components/switch/switch.stories.ts
  packages/components/src/components/switch/switch.tsx
  packages/components/src/components/text-field/text-field.e2e.ts
  packages/components/src/components/text-field/text-field.stories.ts
  packages/components/src/components/text-field/text-field.tsx
Labels: minor

#1379 Documentation update to checkbox, radio-button and states
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/checkbox/checkbox-group-block-states.png
  packages/components/public-storybook/images/checkbox/checkbox-group-inline-states.png
  packages/components/public-storybook/images/radio-button/radio-button-group-block-states.png
  packages/components/public-storybook/images/radio-button/radio-button-group-inline-states.png
  packages/components/src/components/checkbox/Usage.mdx
  packages/components/src/components/radio-button/Usage.mdx
  packages/components/src/stories/foundations/States.mdx
Labels: major

#1380 Switch: Fixed the bug where the sibling elements of switch overlapped with its label
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/switch/switch.e2e.ts
  packages/components/src/components/switch/switch.scss
  packages/components/src/components/switch/switch.tsx
  packages/components/src/index.html
Labels: patch

#1386 Progress bar: aligned progress bar height with the figma design
  examples/wrapper-components/react-javascript/src/components/ProgressBar/ProgressBar.js
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/progress-bar/progress-bar.e2e.ts
  packages/components/src/components/progress-bar/progress-bar.scss
  packages/components/src/components/progress-bar/progress-bar.tsx
  packages/components/src/components/progress-bar/readme.md
Labels: patch

#1394 Navbar: removed burger icon when mobile menu is empty
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/navigation/navbar/navbar.tsx
Labels: minor

#1397 Tailwind CSS page included in Storybook
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/stories/setup-and-installation/TailwindCSS.mdx
Labels: minor
