Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-09, with the labels that each got.

#1445 Basic-table: implement dynamic rows and cols
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/BasicTable/BasicTable.js
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-basic-version/readme.md
  packages/components/src/components/table-basic-version/table.tsx
  packages/components/src/index.html
Labels: minor

#1453 Bugfix: Backgroundcolor of multiselect
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/multi-select/multiselect.scss
Labels: bug, patch

#1462 Bugfix: upgraded tokens version to latest in wrapper libraries
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch

#1499 Fix the yaml file related to deployment to master
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: minor

#1512 Bugfix: Deployment of React Example App Master version
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch
