Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-11, with the labels that each got.

#1557 Accessibility enhancement added to Breadcrumb
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/breadcrumb/breadcrumb-item-label.tsx
  packages/components/src/components/breadcrumb/breadcrumb-item.scss
  packages/components/src/components/breadcrumb/breadcrumb-item.tsx
  packages/components/src/components/breadcrumb/breadcrumb.e2e.ts
  packages/components/src/components/breadcrumb/breadcrumb.tsx
  packages/components/src/components/breadcrumb/readme.md
  packages/components/src/index.html
Labels: minor

#1559 Accessibility enhancement added to Button
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/button/button.tsx
  packages/components/src/components/button/readme.md
  packages/components/src/index.html
Labels: minor

#1564 Navbar-item: removed max-height
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/navigation/navbar/navbar-item.scss
Labels: minor

#1485 Align Radio-Button, Checkbox and Switch to web standards
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/checkbox/checkbox.e2e.ts
  packages/components/src/components/checkbox/checkbox.stories.ts
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/checkbox/readme.md
  packages/components/src/components/chip/chip-item/chip-item.tsx
  packages/components/src/components/radio-button/radio-button.e2e.ts
  packages/components/src/components/radio-button/radio-button.stories.ts
  packages/components/src/components/radio-button/radio-button.tsx
  packages/components/src/components/radio-button/readme.md
  packages/components/src/components/select/multi-select/multiselect.stories.ts
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/multi-select/readme.md
  packages/components/src/components/select/single-select/select.tsx
  packages/components/src/components/switch/readme.md
  packages/components/src/components/switch/switch.e2e.ts
  packages/components/src/components/switch/switch.stories.ts
  packages/components/src/components/switch/switch.tsx
  packages/components/src/components/table-advanced-version/list/list-entry/list-entry.tsx
Labels: major

#1450 Footer: Replaced Prop-based "info links" with slottable links
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/components/Footer/Footer.js
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/components/Footer/Footer.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/components/Footer.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/footer/footer.scss
  packages/components/src/components/footer/footer.stories.ts
  packages/components/src/components/footer/footer.tsx
  packages/components/src/components/link/readme.md
Labels: major

#1571 Accessibility enhancement added to Card, Checkbox, Button, Breadcrumb
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/breadcrumb/breadcrumb-item-label.tsx
  packages/components/src/components/breadcrumb/readme.md
  packages/components/src/components/button/button.tsx
  packages/components/src/components/card/card-headline/card-headline.scss
  packages/components/src/components/card/card-headline/card-headline.tsx
  packages/components/src/components/card/card-headline/readme.md
  packages/components/src/components/card/card.scss
  packages/components/src/components/card/card.tsx
  packages/components/src/components/card/readme.md
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/date-picker/date-picker.tsx
  packages/components/src/components/date-picker/readme.md
Labels: minor

#1584 Sidebar-item: fixed bug where icons were not showing
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/navigation/sidebar/sidebar-item.tsx
  packages/components/src/index.html
Labels: patch

#1581 Dropdown: fixed menu placement bug
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/dropdown/dropdown-menu/dropdown-menu.scss
Labels: patch

#1579 Multi-select: implemented dynamic options update
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/multi-select/multiselect.tsx
Labels: minor

#1588 Single Select: Implemented delete-single-selection button
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/multi-select/multiselect.scss
  packages/components/src/components/select/multi-select/multiselect.tsx
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/select/single-select/select.tsx
Labels: minor

#1546 New component: textarea
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/App.jsx
  examples/wrapper-components/react-vite-js/src/components/Textarea/Textarea.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/Textarea.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-angular/projects/my-app/src/app/app.component.ts
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/button/button.tsx
  packages/components/src/components/overview-table/overview-table.tsx
  packages/components/src/components/textarea/readme.md
  packages/components/src/components/textarea/textarea.e2e.ts
  packages/components/src/components/textarea/textarea.scss
  packages/components/src/components/textarea/textarea.stories.ts
  packages/components/src/components/textarea/textarea.tsx
  packages/components/src/index.html
Labels: minor

#1594 Stepper: implemented `emittedByClick` key in event object emitted by ifxChange
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/stepper/interfaces.tsx
  packages/components/src/components/stepper/step/step.tsx
  packages/components/src/components/stepper/stepper.tsx
  packages/components/src/index.html
Labels: minor

#1592 Date-picker: implemented value, min and max, label and caption props
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/date-picker/date-picker.scss
  packages/components/src/components/date-picker/date-picker.stories.ts
  packages/components/src/components/date-picker/date-picker.tsx
  packages/components/src/components/date-picker/readme.md
  packages/components/src/index.html
Labels: minor

#1606 Stencil/core updated to 4.22.3. RangeError in React now resolved
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: bug, patch

#1608 Basic-table: reverts back previously made feature changes enabling dynamic updates
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/table-basic-version/readme.md
  packages/components/src/components/table-basic-version/table.stories.ts
  packages/components/src/components/table-basic-version/table.tsx
  packages/components/src/index.html
Labels: minor

#1612 Datepicker: fixed focused-state style of calendar icon
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/date-picker/date-picker.scss
Labels: patch

#1609 Stepper: implement vertical stepper and improved responsiveness
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/stepper/Development.mdx
  packages/components/src/components/stepper/interfaces.tsx
  packages/components/src/components/stepper/readme.md
  packages/components/src/components/stepper/step/step.scss
  packages/components/src/components/stepper/step/step.tsx
  packages/components/src/components/stepper/stepper.scss
  packages/components/src/components/stepper/stepper.stories.ts
  packages/components/src/components/stepper/stepper.tsx
Labels: minor

#1605 Accessibility enhancement added to Chip
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/chip/chip-item/chip-item.scss
  packages/components/src/components/chip/chip-item/chip-item.tsx
  packages/components/src/components/chip/chip.scss
  packages/components/src/components/chip/chip.tsx
  packages/components/src/components/chip/readme.md
Labels: enhancement, minor

#1602 Stepper: added documentation
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/stepper/stepper-hor-default-flexible.png
  packages/components/public-storybook/images/stepper/stepper-ver-default-flexible.png
  packages/components/src/components/stepper/Usage.mdx
Labels: minor

#1614 Multi-select: made search-field position fixed on scroll
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/multi-select/multiselect.scss
Labels: patch

#1561 Bugfix: Use canary release of Tokens package to consume fonts from CDN
  examples/stencil-components/vanilla-cdn/index.html
  examples/stencil-components/vanilla-cdn/package.json
  examples/stencil-components/vanilla-cdn/readme.md
  examples/stencil-components/vanilla-cdn/update-link.js
  examples/stencil-components/vanilla-cdn/vite.config.js
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch

#1616 Text-field: implemented a delete button to clear the text content
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/text-field/readme.md
  packages/components/src/components/text-field/text-field.scss
  packages/components/src/components/text-field/text-field.stories.ts
  packages/components/src/components/text-field/text-field.tsx
Labels: minor
