Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-02, with the labels that each got.

#948 Bugfix: text field uses wrong font size and styling not aligned
  packages/components/src/components/select/multi-select/multiselect.scss
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/text-field/text-field.scss
Labels: bug, patch

#952 Bugfix: font file import updated for storybook
  .gitignore
  examples/stencil-components/vanilla-cdn/index.html
  examples/stencil-components/vanilla-cdn/package-lock.json
  examples/stencil-components/vanilla-cdn/package.json
  examples/stencil-components/vanilla-cdn/update-link.js
  examples/wrapper-components/react-javascript/package.json
  examples/wrapper-components/react-javascript/src/App.scss
  examples/wrapper-components/react-typescript/package-lock.json
  examples/wrapper-components/vue-javascript/package-lock.json
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/assets/base.scss
  examples/wrapper-components/vue-typescript/package-lock.json
  lerna.json
  package-lock.json
  package.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/app/app.component.scss
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/.npmrc
  packages/components/.storybook/ifxTheme.js
  packages/components/.storybook/main.js
  packages/components/.storybook/manager-head.html
  packages/components/.storybook/preview-head.html
  packages/components/.storybook/preview.js
  packages/components/.storybook/webpack.config.js
  packages/components/package.json
  packages/components/src/components/tabs/tabs.tsx
  packages/components/src/global/global.scss
  packages/components/stencil.config.ts
Labels: patch

#976 Enhancement: footer links now customizable and removable + bump copyright date to current date
  packages/components-vue/lib/components.ts
  packages/components/.gitignore
  packages/components/src/components/footer/footer-column.scss
  packages/components/src/components/footer/footer-column.tsx
  packages/components/src/components/footer/footer.scss
  packages/components/src/components/footer/footer.stories.ts
  packages/components/src/components/footer/footer.tsx
Labels: minor

#978 Bugfix: Multiselect options: handling of parent - child relationship
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/select/multi-select/multiselect.tsx
Labels: patch

#975 Fixed the height and width of the switch container
  packages/components/src/components/switch/switch.scss
Labels: patch

#974 Sidebar: implemented initial-collapse prop
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/components/Sidebar/Sidebar.js
  package-lock.json
  package.json
  packages/components-vue/lib/components.ts
  packages/components/src/components/sidebar/readme.md
  packages/components/src/components/sidebar/sidebar-item.tsx
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/components/sidebar/sidebar.tsx
  packages/components/src/index.html
Labels: minor

#1009 Sidebar header is now removable
  packages/components-vue/lib/components.ts
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/components/sidebar/sidebar.tsx
Labels: minor

#994 Sidebar: links are now removable
  examples/stencil-components/vanilla-cdn/index.html
  packages/components-vue/lib/components.ts
  packages/components/src/components/sidebar/sidebar.scss
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/components/sidebar/sidebar.tsx
  packages/components/src/index.html
Labels: minor

#1011 Implemented sidebar header component
  .github/workflows/github_pages_storybook_preview.yml
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  .gitignore
  examples/stencil-components/vanilla-cdn/index.html
  package-lock.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-react/package.json
  packages/components-vue/lib/components.ts
  packages/components-vue/package.json
  packages/components/src/components/sidebar/readme.md
  packages/components/src/components/sidebar/sidebar-title.scss
  packages/components/src/components/sidebar/sidebar-title.tsx
  packages/components/src/components/sidebar/sidebar.scss
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/index.html
Labels: minor
