Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-06, with the labels that each got.

#1283 Navbar and Sidebar moved into a Navigation folder on Storybook
  packages/components/src/components/icon/readme.md
  packages/components/src/components/navigation/navbar/Development.mdx
  packages/components/src/components/navigation/navbar/Usage.mdx
  packages/components/src/components/navigation/navbar/assets/default_image.png
  packages/components/src/components/navigation/navbar/assets/default_profile2.png
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar-item.tsx
  packages/components/src/components/navigation/navbar/navbar-profile.tsx
  packages/components/src/components/navigation/navbar/navbar.scss
  packages/components/src/components/navigation/navbar/navbar.stories.ts
  packages/components/src/components/navigation/navbar/navbar.tsx
  packages/components/src/components/navigation/navbar/readme.md
  packages/components/src/components/navigation/sidebar/Development.mdx
  packages/components/src/components/navigation/sidebar/Usage.mdx
  packages/components/src/components/navigation/sidebar/readme.md
  packages/components/src/components/navigation/sidebar/sidebar-item.scss
  packages/components/src/components/navigation/sidebar/sidebar-item.tsx
  packages/components/src/components/navigation/sidebar/sidebar-title.scss
  packages/components/src/components/navigation/sidebar/sidebar-title.tsx
  packages/components/src/components/navigation/sidebar/sidebar.e2e.ts
  packages/components/src/components/navigation/sidebar/sidebar.scss
  packages/components/src/components/navigation/sidebar/sidebar.stories.ts
  packages/components/src/components/navigation/sidebar/sidebar.tsx
  packages/components/src/components/number-indicator/readme.md
  packages/components/src/components/overview-table/overview-table.tsx
Labels: minor

#1282 Enhancement: Updated Documentation with vue-cli usage related information
  packages/components/README.md
  packages/components/src/stories/setup-and-installation/framework-integration/VueWrappers.mdx
Labels: minor

#1252 Pagination: page number centered + padding increased
  packages/components/src/components/pagination/pagination.scss
Labels: patch

#1290 Date-picker: Added documentation
  packages/components/public-storybook/images/date-picker/date-picker-anatomy.png
  packages/components/public-storybook/images/date-picker/date-picker-sizes.png
  packages/components/public-storybook/images/date-picker/date-picker-states.png
  packages/components/src/components/date-picker/Usage.mdx
Labels: enhancement

#1292 Search-field: implement ```placeholder``` prop to customize placeholder text
  packages/components/src/components/search-field/readme.md
  packages/components/src/components/search-field/search-field.stories.ts
  packages/components/src/components/search-field/search-field.tsx
Labels: minor

#1186 Enhancement: Add configurable step size to slider component
  packages/components/src/components/slider/readme.md
  packages/components/src/components/slider/slider.e2e.tsx
  packages/components/src/components/slider/slider.stories.tsx
  packages/components/src/components/slider/slider.tsx
Labels: minor

#1303 Multi-select: Fixed a bug causing error when unselecting option
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/checkbox/readme.md
  packages/components/src/components/select/multi-select/interfaces.tsx
  packages/components/src/components/select/multi-select/multiselect.tsx
Labels: minor
