Repository Infineon/infineon-design-system-stencil, pull requests merged in 2024-04, with the labels that each got.

#1121 Progress bar: fixed bug where label text looked broken
  packages/components/src/components/progress-bar/progress-bar.tsx
Labels: patch

#1133 Bugfix: revert reversion of documentation changes
  packages/components/public-storybook/images/link/link-bold-states.png
  packages/components/public-storybook/images/link/link-menu-states.png
  packages/components/public-storybook/images/link/link-title-states.png
  packages/components/public-storybook/images/link/link-underline-states.png
  packages/components/public-storybook/images/search-input/search-recent-suggest.png
  packages/components/public-storybook/images/search-input/search-suggest-search.png
  packages/components/public-storybook/images/sidebar/navigation-bar-variant.png
  packages/components/public-storybook/images/sidebar/sidebar-anatomy.png
  packages/components/public-storybook/images/sidebar/sidebar-expanded-anatomy.png
  packages/components/public-storybook/images/sidebar/sidebar-sections.png
  packages/components/public-storybook/images/table-basic-version/table-content-template-items.png
  packages/components/public-storybook/images/table-basic-version/table-example-compact.png
  packages/components/public-storybook/images/table-basic-version/table-example-default.png
  packages/components/public-storybook/images/table-basic-version/table-header-column-action-reorder.png
  packages/components/public-storybook/images/table-basic-version/table-header-column-action-resize.png
  packages/components/public-storybook/images/table-basic-version/table-header-content-logic.png
  packages/components/public-storybook/images/table-basic-version/table-header-template-items.png
  packages/components/src/components/modal/Usage.mdx
  packages/components/src/components/search-field/Usage.mdx
  packages/components/src/components/sidebar/Usage.mdx
  packages/components/src/components/table-basic-version/Usage.mdx
Labels: patch

#941 Navbar: version 2
  .gitignore
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/package.json
  examples/wrapper-components/react-javascript/src/assets/default_profile2.png
  examples/wrapper-components/react-javascript/src/components/Navbar/Navbar.js
  examples/wrapper-components/react-typescript/src/components/Navbar/Navbar.tsx
  examples/wrapper-components/vue-javascript/src/components/Navbar.vue
  examples/wrapper-components/vue-typescript/src/components/Navbar.vue
  package-lock.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-vue/lib/components.ts
  packages/components-vue/lib/vue-component-lib/utils.ts
  packages/components/public-storybook/images/navbar/default_image.png
  packages/components/src/components/navbar/Development.mdx
  packages/components/src/components/navbar/assets/default_image.png
  packages/components/src/components/navbar/assets/default_profile2.png
  packages/components/src/components/navbar/navbar-item.scss
  packages/components/src/components/navbar/navbar-item.tsx
  packages/components/src/components/navbar/navbar-menu-item.scss
  packages/components/src/components/navbar/navbar-menu-item.tsx
  packages/components/src/components/navbar/navbar-menu.scss
  packages/components/src/components/navbar/navbar-menu.tsx
  packages/components/src/components/navbar/navbar-profile.tsx
  packages/components/src/components/navbar/navbar.scss
  packages/components/src/components/navbar/navbar.stories.ts
  packages/components/src/components/navbar/navbar.tsx
  packages/components/src/components/navbar/readme.md
  packages/components/src/components/search-bar/readme.md
  packages/components/src/components/search-bar/search-bar.tsx
  packages/components/src/components/sidebar/sidebar-item.tsx
  packages/components/src/index.html
Labels: major

#1140 Master deployment workflow fails
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  package-lock.json
Labels: patch

#1145 Bugfix: missing line added to master depoyment file
  .github/workflows/shipit_master_and_example_apps_deployment.yml
  package-lock.json
  packages/components-react/package.json
Labels: patch

#1171 Bugfix: dependency updates after dependabot merge
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  package-lock.json
  package.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components/.npmrc
  packages/components/.storybook/main.js
  packages/components/package.json
  packages/components/src/components/accordion/accordion.stories.tsx
  packages/components/src/components/alert/alert.stories.ts
  packages/components/src/components/badge/badge.stories.ts
  packages/components/src/components/breadcrumb/breadcrumb.stories.ts
  packages/components/src/components/button/button.stories.ts
  packages/components/src/components/card/card.stories.ts
  packages/components/src/components/checkbox/checkbox.stories.ts
  packages/components/src/components/chips/chip.stories.ts
  packages/components/src/components/dropdown/dropdown.stories.ts
  packages/components/src/components/footer/footer.stories.ts
  packages/components/src/components/icon-button/icon-button.stories.ts
  packages/components/src/components/icon/infineonIconStencil.stories.ts
  packages/components/src/components/icons-preview/icons-preview.stories.ts
  packages/components/src/components/link/link.stories.ts
  packages/components/src/components/modal/modal.stories.ts
  packages/components/src/components/navbar/navbar.stories.ts
  packages/components/src/components/number-indicator/number-indicator.stories.ts
  packages/components/src/components/pagination/pagination.stories.ts
  packages/components/src/components/progress-bar/progress-bar.stories.ts
  packages/components/src/components/radio-button/radio-button.stories.ts
  packages/components/src/components/search-bar/search-bar.stories.ts
  packages/components/src/components/search-field/search-field.stories.ts
  packages/components/src/components/select/multi-select/multiselect.stories.ts
  packages/components/src/components/select/single-select/select.stories.ts
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/components/slider/slider.stories.tsx
  packages/components/src/components/spinner/spinner.stories.ts
  packages/components/src/components/status/status.stories.ts
  packages/components/src/components/switch/switch.stories.ts
  packages/components/src/components/table-basic-version/table.stories.ts
  packages/components/src/components/table/table.stories.ts
  packages/components/src/components/tabs/tabs.stories.tsx
  packages/components/src/components/tag/tag.stories.ts
  packages/components/src/components/text-field/text-field.stories.ts
  packages/components/src/components/tooltip/tooltip.stories.ts
  packages/components/src/stories/Icons.mdx
  packages/components/src/stories/setup-and-installation/About.mdx
  packages/components/src/stories/setup-and-installation/GettingStarted.mdx
  packages/components/src/stories/setup-and-installation/faq/FAQ.mdx
  packages/components/src/stories/setup-and-installation/framework-integration/AngularWrappers.mdx
  packages/components/src/stories/setup-and-installation/framework-integration/ReactWrappers.mdx
  packages/components/src/stories/setup-and-installation/framework-integration/VueWrappers.mdx
  packages/components/src/stories/setup-and-installation/framework-integration/WrapperComponents.mdx
Labels: patch

#1115 Sidebar: optimized the padding of ifx-sidebar-item
  packages/components/src/components/sidebar/sidebar-item.scss
  packages/components/src/components/sidebar/sidebar-item.tsx
  packages/components/src/components/sidebar/sidebar.stories.ts
  packages/components/src/components/sidebar/sidebar.tsx
  packages/components/src/index.html
Labels: patch

#854 752 component stepper
  .github/workflows/shipit_pr_and_example_apps_deployment.yml
  .gitignore
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-javascript/src/App.js
  examples/wrapper-components/react-javascript/src/components/Stepper/Stepper.js
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/Stepper.vue
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/lib/components/stencil-generated/index.ts
  packages/components-react/lib/index.ts
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icon/readme.md
  packages/components/src/components/stepper/readme.md
  packages/components/src/components/stepper/step/readme.md
  packages/components/src/components/stepper/step/step.scss
  packages/components/src/components/stepper/step/step.tsx
  packages/components/src/components/stepper/stepper.scss
  packages/components/src/components/stepper/stepper.stories.ts
  packages/components/src/components/stepper/stepper.tsx
  packages/components/src/components/tabs/tabs.stories.ts
Labels: minor

#1157 Slider: Implement range slider (two thumb)
  examples/wrapper-components/react-javascript/src/components/Slider/Slider.js
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components/src/components/slider/readme.md
  packages/components/src/components/slider/slider.e2e.tsx
  packages/components/src/components/slider/slider.scss
  packages/components/src/components/slider/slider.stories.tsx
  packages/components/src/components/slider/slider.tsx
  packages/components/src/index.html
Labels: minor

#1192 Storybook: code snippet bug fix
  package-lock.json
  package.json
  packages/components/package.json
Labels: patch

#1183 Tooltip: hid tooltip when hovered
  packages/components/src/components/tooltip/tooltip.tsx
Labels: minor

#1180 Tabs: Implement a feature to insert an icon before or after tab header
  examples/wrapper-components/react-javascript/src/components/Tabs/Tabs.js
  packages/components/src/components/icon/readme.md
  packages/components/src/components/tabs/readme.md
  packages/components/src/components/tabs/tab.tsx
  packages/components/src/components/tabs/tabs.scss
  packages/components/src/components/tabs/tabs.stories.ts
  packages/components/src/components/tabs/tabs.tsx
Labels: minor

#1141 Modal: implemented width property
  examples/wrapper-components/react-javascript/src/components/Modal/Modal.js
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/modal/modal.stories.ts
  packages/components/src/components/modal/modal.tsx
  packages/components/src/components/modal/readme.md
Labels: minor

#1155 Modal: Removed default focus on buttons
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/modal/modal.tsx
  packages/components/src/index.html
  packages/components/src/stories/foundations/Typography.mdx
Labels: patch

#1195 Storybook: fix the bug where snippet code in a stories appeared twice
  .github/workflows/github_pages_storybook_preview.yml
  packages/components/src/components/modal/Development.mdx
  packages/components/src/components/navbar/navbar.tsx
  packages/components/src/components/table-basic-version/Development.mdx
Labels: patch

#1197 Modal: Fix issue with rendering lines
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/modal/modal.tsx
Labels: patch
