Repository Infineon/infineon-design-system-stencil, pull requests merged in 2025-02, with the labels that each got.

#1496 Storybook: Introduces DDS Templates
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  package.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/package.json
  packages/components/.storybook/main.js
  packages/components/package.json
  packages/components/src/components/alert/readme.md
  packages/components/src/components/button/readme.md
  packages/components/src/components/icon-button/readme.md
  packages/components/src/components/link/readme.md
  packages/components/src/components/spinner/readme.md
  packages/components/src/components/templates/assets/table_template.png
  packages/components/src/components/templates/assets/wizard_template.png
  packages/components/src/components/templates/template/readme.md
  packages/components/src/components/templates/template/template.scss
  packages/components/src/components/templates/template/template.tsx
  packages/components/src/components/templates/templates-ui/readme.md
  packages/components/src/components/templates/templates-ui/templates-ui.scss
  packages/components/src/components/templates/templates-ui/templates-ui.tsx
  packages/components/src/components/text-field/readme.md
  packages/components/src/index.ts
  packages/components/src/stories/Templates.mdx
  packages/components/stencil.config.ts
Labels: minor

#1678 Status: adds all token colors as available options
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/components/Status/Status.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/components/Status.vue
  lerna.json
  package-lock.json
  package.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/status/readme.md
  packages/components/src/components/status/status.scss
  packages/components/src/components/status/status.stories.ts
  packages/components/src/components/status/status.tsx
Labels: minor

#1716 Updates Button, Status and Table documentation
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/button/button-sizes.png
  packages/components/public-storybook/images/status/status-variant-outline.png
  packages/components/public-storybook/images/table-basic-version/table-cell-button-items.png
  packages/components/public-storybook/images/table-basic-version/table-cell-checkbox-items.png
  packages/components/public-storybook/images/table-basic-version/table-cell-status-items.png
  packages/components/public-storybook/images/table-basic-version/table-cell-text-items.png
  packages/components/public-storybook/images/table-basic-version/table-cell-tree-items.png
  packages/components/public-storybook/images/table-basic-version/table-content-template-items.png
  packages/components/public-storybook/images/table-basic-version/table-example-compact.png
  packages/components/public-storybook/images/table-basic-version/table-example-default.png
  packages/components/public-storybook/images/table-basic-version/table-header-column-action-reorder.png
  packages/components/public-storybook/images/table-basic-version/table-header-column-action-resize.png
  packages/components/public-storybook/images/table-basic-version/table-header-content-logic-zebra.png
  packages/components/public-storybook/images/table-basic-version/table-header-content-logic.png
  packages/components/public-storybook/images/table-basic-version/table-header-sorting-items.png
  packages/components/public-storybook/images/table-basic-version/table-header-template-items.png
  packages/components/src/components/button/Usage.mdx
  packages/components/src/components/table-basic-version/Usage.mdx
Labels: patch

#1722 Textarea: implements full-width prop
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/textarea/readme.md
  packages/components/src/components/textarea/textarea.scss
  packages/components/src/components/textarea/textarea.stories.ts
  packages/components/src/components/textarea/textarea.tsx
  packages/components/src/index.html
Labels: minor

#1697 Pagination: implements items per page prop
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/components/Pagination/Pagination.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/components/Pagination.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/pagination/pagination.stories.ts
  packages/components/src/components/pagination/pagination.tsx
  packages/components/src/components/pagination/readme.md
  packages/components/src/components/select/single-select/select.tsx
  packages/components/src/components/table-advanced-version/table.tsx
Labels: major

#1681 New component: Checkbox-group
  examples/stencil-components/vanilla-cdn/index.html
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/App.jsx
  examples/wrapper-components/react-vite-js/src/components/CheckboxGroup/CheckboxGroup.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/App.vue
  examples/wrapper-components/vue-javascript/src/components/CheckboxGroup.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-react/src/components.ts
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/checkbox-group/checkbox-group.e2e.ts
  packages/components/src/components/checkbox-group/checkbox-group.scss
  packages/components/src/components/checkbox-group/checkbox-group.stories.ts
  packages/components/src/components/checkbox-group/checkbox-group.tsx
  packages/components/src/components/checkbox-group/readme.md
  packages/components/src/components/checkbox/checkbox.scss
  packages/components/src/components/checkbox/checkbox.stories.ts
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/checkbox/readme.md
  packages/components/src/components/icon/readme.md
Labels: minor

#1725 Status and Content Switcher: documentation update
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/public-storybook/images/content-switcher/content-switcher-variants.png
  packages/components/src/components/content-switcher/Usage.mdx
  packages/components/src/components/status/Usage.mdx
Labels: patch

#1731 Single select: removes reserved space for inactive dropdown
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/single-select/select.scss
Labels: patch

#1735 ifx-select: prevents dropdown menu from closing on search-field click
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/single-select/select.tsx
Labels: minor

#1747 Link: implements download prop
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/link/link.stories.ts
  packages/components/src/components/link/link.tsx
  packages/components/src/components/link/readme.md
Labels: minor

#1750 Resolves rollup error on React app
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch
