Repository Infineon/infineon-design-system-stencil, pull requests merged in 2025-06, with the labels that each got.

#1879 Single-select: exposes clear method for public use
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/select/single-select/readme.md
  packages/components/src/components/select/single-select/select.stories.ts
  packages/components/src/components/select/single-select/select.tsx
Labels: minor

#1885 Segmented control: prevents default item selection
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/segmented-control/segmented-control.tsx
Labels: patch

#1845 Resolves issue with font-family not working on Mac
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/accordion.scss
  packages/components/src/components/accordion/accordionItem.scss
  packages/components/src/components/alert/alert.scss
  packages/components/src/components/badge/badge.scss
  packages/components/src/components/breadcrumb/breadcrumb-item.scss
  packages/components/src/components/breadcrumb/breadcrumb.scss
  packages/components/src/components/button/button.scss
  packages/components/src/components/card/card-headline/card-headline.scss
  packages/components/src/components/card/card.scss
  packages/components/src/components/checkbox-group/checkbox-group.scss
  packages/components/src/components/content-switcher/content-switcher-item.scss
  packages/components/src/components/dropdown/dropdown-header/dropdown-header.scss
  packages/components/src/components/dropdown/dropdown-item/dropdown-item.scss
  packages/components/src/components/dropdown/dropdown-menu/dropdown-menu.scss
  packages/components/src/components/footer/footer-column.scss
  packages/components/src/components/footer/footer.scss
  packages/components/src/components/icon-button/icon-button.scss
  packages/components/src/components/link/link.scss
  packages/components/src/components/modal/modal.scss
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar.scss
  packages/components/src/components/navigation/sidebar/sidebar-item.scss
  packages/components/src/components/navigation/sidebar/sidebar.scss
  packages/components/src/components/notification/notification.scss
  packages/components/src/components/pagination/pagination.scss
  packages/components/src/components/progress-bar/progress-bar.scss
  packages/components/src/components/radio-button-group/radio-button-group.scss
  packages/components/src/components/radio-button/radio-button.scss
  packages/components/src/components/search-bar/search-bar.scss
  packages/components/src/components/search-field/search-field.scss
  packages/components/src/components/select/multi-select/multiselect.scss
  packages/components/src/components/select/single-select/select.scss
  packages/components/src/components/status/status.scss
  packages/components/src/components/table-advanced-version/filter-type-group/filter-search/filter-search.scss
  packages/components/src/components/table-advanced-version/table.scss
  packages/components/src/components/table-basic-version/table.scss
  packages/components/src/components/tabs/tabs.scss
  packages/components/src/components/tag/tag.scss
  packages/components/src/components/text-field/text-field.scss
  packages/components/src/components/tooltip/tooltip.scss
  packages/components/src/global/font.scss
Labels: patch

#1889 Angular: updates to latest version 20
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/component-library/src/lib/component-library.module.ts
  packages/components-angular/projects/my-app/src/app/app.module.ts
  packages/components-angular/projects/my-app/src/main.ts
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/stories/setup-and-installation/framework-integration/AngularWrappers.mdx
Labels: minor

#1894 Updates the repository README to document the additional steps for Mac users when using the CDN link
  README.md
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
Labels: patch

#1899 Modal: fixes bug where correct window height is not detected on Edge browser causing content overflow
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/modal/modal.tsx
Labels: minor

#1900 Storybook: adds a search feature in the icon library
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icons-preview/icons-preview.scss
  packages/components/src/components/icons-preview/icons-preview.tsx
  packages/components/src/components/icons-preview/readme.md
  packages/components/src/components/search-field/readme.md
Labels: minor

#1905 Makes the icon prop of icon and icon-button components dynamic
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icon-button/icon-button.tsx
  packages/components/src/components/icon/infineonIconStencil.tsx
Labels: minor

#1896 Icons: replaces all existing icons with single 16px-sized icons
  examples/wrapper-components/react-javascript/src/components/Alert/Alert.js
  examples/wrapper-components/react-vite-js/package-lock.json
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/react-vite-js/src/components/Alert/Alert.jsx
  examples/wrapper-components/vue-javascript/package.json
  examples/wrapper-components/vue-javascript/src/components/Alert.vue
  examples/wrapper-components/vue-javascript/src/components/Tooltip.vue
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-angular/projects/my-app/src/app/app.component.html
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/accordionItem.scss
  packages/components/src/components/accordion/accordionItem.tsx
  packages/components/src/components/alert/alert.e2e.ts
  packages/components/src/components/alert/alert.stories.ts
  packages/components/src/components/breadcrumb/breadcrumb-item-label.tsx
  packages/components/src/components/checkbox/checkbox.tsx
  packages/components/src/components/chip/chip-item/chip-item.tsx
  packages/components/src/components/dropdown/dropdown-trigger-button/dropdown-trigger-button.tsx
  packages/components/src/components/file-upload/file-upload.tsx
  packages/components/src/components/icon-button/icon-button.stories.ts
  packages/components/src/components/icon/infineonIconStencil.tsx
  packages/components/src/components/icons-preview/icons-preview.tsx
  packages/components/src/components/modal/modal.stories.ts
  packages/components/src/components/modal/modal.tsx
  packages/components/src/components/navigation/navbar/navbar-item.scss
  packages/components/src/components/navigation/navbar/navbar-item.tsx
  packages/components/src/components/navigation/navbar/navbar.tsx
  packages/components/src/components/navigation/sidebar/sidebar-item.tsx
  packages/components/src/components/overview-table/overview-table.tsx
  packages/components/src/components/pagination/pagination.tsx
  packages/components/src/components/stepper/step/step.tsx
  packages/components/src/components/table-advanced-version/list/list.tsx
  packages/components/src/components/table-advanced-version/table.tsx
  packages/components/src/components/templates/templates-ui/templates-ui.tsx
  packages/components/src/components/tooltip/tooltip.stories.ts
  packages/components/src/stories/setup-and-installation/GettingStarted.mdx
Labels: major

#1915 Updates icon name validation to only accept camelCase and kebab-case
  examples/wrapper-components/react-vite-js/package.json
  examples/wrapper-components/vue-javascript/package.json
  lerna.json
  package-lock.json
  packages/components-angular/package.json
  packages/components-angular/projects/component-library/package.json
  packages/components-react/package.json
  packages/components-vue/package.json
  packages/components/package.json
  packages/components/src/components/icon/infineonIconStencil.tsx
Labels: minor
